//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class ChangeDisplayServiceRequest : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/ChangeDisplayService";
        public override string RosMessageName => k_RosMessageName;

        public int flag;
        //  flag determines the display of the game to feature

        public ChangeDisplayServiceRequest()
        {
            this.flag = 0;
        }

        public ChangeDisplayServiceRequest(int flag)
        {
            this.flag = flag;
        }

        public static ChangeDisplayServiceRequest Deserialize(MessageDeserializer deserializer) => new ChangeDisplayServiceRequest(deserializer);

        private ChangeDisplayServiceRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.flag);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.flag);
        }

        public override string ToString()
        {
            return "ChangeDisplayServiceRequest: " +
            "\nflag: " + flag.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
