//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class ChangeDisplayServiceResponse : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/ChangeDisplayService";
        public override string RosMessageName => k_RosMessageName;


        public ChangeDisplayServiceResponse()
        {
        }
        public static ChangeDisplayServiceResponse Deserialize(MessageDeserializer deserializer) => new ChangeDisplayServiceResponse(deserializer);

        private ChangeDisplayServiceResponse(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "ChangeDisplayServiceResponse: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
